# Generated by skir-elixir-gen. Do not edit this file manually.

defmodule SkirOut.UnitTest do
  @moduledoc false
  use Skir.Struct

  field :test_number, :int32, 0
  field :assertion, SkirOut.Assertion, 1
end

defmodule SkirOut.Assertion.BytesEqual do
  @moduledoc false

  use Skir.Struct

  field :actual, SkirOut.BytesExpression, 0
  field :expected, SkirOut.BytesExpression, 1
end

defmodule SkirOut.Assertion.BytesIn do
  @moduledoc false

  use Skir.Struct

  field :actual, SkirOut.BytesExpression, 0
  field :expected, {:array, :bytes}, 1
end

defmodule SkirOut.Assertion.StringEqual do
  @moduledoc false

  use Skir.Struct

  field :actual, SkirOut.StringExpression, 0
  field :expected, SkirOut.StringExpression, 1
end

defmodule SkirOut.Assertion.StringIn do
  @moduledoc false

  use Skir.Struct

  field :actual, SkirOut.StringExpression, 0
  field :expected, {:array, :string}, 1
end

defmodule SkirOut.Assertion.ReserializeValue do
  @moduledoc false

  use Skir.Struct

  field :value, SkirOut.TypedValue, 0
  field :expected_dense_json, {:array, :string}, 1
  field :expected_readable_json, {:array, :string}, 2
  field :alternative_jsons, {:array, SkirOut.StringExpression}, 3
  field :expected_bytes, {:array, :bytes}, 4
  field :alternative_bytes, {:array, SkirOut.BytesExpression}, 5
  field :expected_type_descriptor, {:optional, :string}, 6
end

defmodule SkirOut.Assertion.ReserializeLargeString do
  @moduledoc false

  use Skir.Struct

  field :num_chars, :int32, 0
  field :expected_byte_prefix, :bytes, 1
end

defmodule SkirOut.Assertion.ReserializeLargeArray do
  @moduledoc false

  use Skir.Struct

  field :num_items, :int32, 0
  field :expected_byte_prefix, :bytes, 1
end

defmodule SkirOut.Assertion.EnumAFromJsonIsConstant do
  @moduledoc false

  use Skir.Struct

  field :actual, SkirOut.StringExpression, 0
  field :keep_unrecognized, :bool, 1
end

defmodule SkirOut.Assertion.EnumAFromBytesIsConstant do
  @moduledoc false

  use Skir.Struct

  field :actual, SkirOut.BytesExpression, 0
  field :keep_unrecognized, :bool, 1
end

defmodule SkirOut.Assertion.EnumBFromJsonIsWrapperB do
  @moduledoc false

  use Skir.Struct

  field :actual, SkirOut.StringExpression, 0
  field :expected, :string, 1
  field :keep_unrecognized, :bool, 2
end

defmodule SkirOut.Assertion.EnumBFromBytesIsWrapperB do
  @moduledoc false

  use Skir.Struct

  field :actual, SkirOut.BytesExpression, 0
  field :expected, :string, 1
  field :keep_unrecognized, :bool, 2
end

defmodule SkirOut.Assertion do
  @moduledoc false

  use Skir.Enum

  variant :bytes_equal, 1, wraps: SkirOut.Assertion.BytesEqual
  variant :bytes_in, 2, wraps: SkirOut.Assertion.BytesIn
  variant :string_equal, 3, wraps: SkirOut.Assertion.StringEqual
  variant :string_in, 4, wraps: SkirOut.Assertion.StringIn
  variant :reserialize_value, 5, wraps: SkirOut.Assertion.ReserializeValue
  variant :reserialize_large_string, 6, wraps: SkirOut.Assertion.ReserializeLargeString
  variant :reserialize_large_array, 7, wraps: SkirOut.Assertion.ReserializeLargeArray
  variant :enum_a_from_json_is_constant, 8, wraps: SkirOut.Assertion.EnumAFromJsonIsConstant
  variant :enum_a_from_bytes_is_constant, 9, wraps: SkirOut.Assertion.EnumAFromBytesIsConstant
  variant :enum_b_from_json_is_wrapper_b, 10, wraps: SkirOut.Assertion.EnumBFromJsonIsWrapperB
  variant :enum_b_from_bytes_is_wrapper_b, 11, wraps: SkirOut.Assertion.EnumBFromBytesIsWrapperB
end

defmodule SkirOut.StringExpression do
  @moduledoc false

  use Skir.Enum

  variant :literal, 1, wraps: :string
  variant :to_dense_json, 2, wraps: SkirOut.TypedValue
  variant :to_readable_json, 3, wraps: SkirOut.TypedValue
end

defmodule SkirOut.BytesExpression do
  @moduledoc false

  use Skir.Enum

  variant :literal, 1, wraps: :bytes
  variant :to_bytes, 2, wraps: SkirOut.TypedValue
end

defmodule SkirOut.TypedValue do
  @moduledoc false

  use Skir.Enum

  variant :bool, 1, wraps: :bool
  variant :int32, 2, wraps: :int32
  variant :int64, 3, wraps: :int64
  variant :hash64, 4, wraps: :hash64
  variant :float32, 5, wraps: :float32
  variant :float64, 6, wraps: :float64
  variant :timestamp, 7, wraps: :timestamp
  variant :string, 8, wraps: :string
  variant :bytes, 9, wraps: :bytes
  variant :bool_optional, 10, wraps: {:optional, :bool}
  variant :ints, 11, wraps: {:array, :int32}
  variant :point, 12, wraps: SkirOut.Point
  variant :color, 13, wraps: SkirOut.Color
  variant :my_enum, 14, wraps: SkirOut.MyEnum
  variant :enum_a, 15, wraps: SkirOut.EnumA
  variant :enum_b, 16, wraps: SkirOut.EnumB
  variant :keyed_arrays, 17, wraps: SkirOut.KeyedArrays
  variant :rec_struct, 18, wraps: SkirOut.RecStruct
  variant :rec_enum, 19, wraps: SkirOut.RecEnum
  variant :round_trip_dense_json, 20, wraps: SkirOut.TypedValue
  variant :round_trip_readable_json, 21, wraps: SkirOut.TypedValue
  variant :round_trip_bytes, 22, wraps: SkirOut.TypedValue
  variant :point_from_json_keep_unrecognized, 23, wraps: SkirOut.StringExpression
  variant :point_from_json_drop_unrecognized, 24, wraps: SkirOut.StringExpression
  variant :point_from_bytes_keep_unrecognized, 25, wraps: SkirOut.BytesExpression
  variant :point_from_bytes_drop_unrecognized, 26, wraps: SkirOut.BytesExpression
  variant :color_from_json_keep_unrecognized, 27, wraps: SkirOut.StringExpression
  variant :color_from_json_drop_unrecognized, 28, wraps: SkirOut.StringExpression
  variant :color_from_bytes_keep_unrecognized, 29, wraps: SkirOut.BytesExpression
  variant :color_from_bytes_drop_unrecognized, 30, wraps: SkirOut.BytesExpression
  variant :my_enum_from_json_keep_unrecognized, 31, wraps: SkirOut.StringExpression
  variant :my_enum_from_json_drop_unrecognized, 32, wraps: SkirOut.StringExpression
  variant :my_enum_from_bytes_keep_unrecognized, 33, wraps: SkirOut.BytesExpression
  variant :my_enum_from_bytes_drop_unrecognized, 34, wraps: SkirOut.BytesExpression
  variant :enum_a_from_json_keep_unrecognized, 35, wraps: SkirOut.StringExpression
  variant :enum_a_from_json_drop_unrecognized, 36, wraps: SkirOut.StringExpression
  variant :enum_a_from_bytes_keep_unrecognized, 37, wraps: SkirOut.BytesExpression
  variant :enum_a_from_bytes_drop_unrecognized, 38, wraps: SkirOut.BytesExpression
  variant :enum_b_from_json_keep_unrecognized, 39, wraps: SkirOut.StringExpression
  variant :enum_b_from_json_drop_unrecognized, 40, wraps: SkirOut.StringExpression
  variant :enum_b_from_bytes_keep_unrecognized, 41, wraps: SkirOut.BytesExpression
  variant :enum_b_from_bytes_drop_unrecognized, 42, wraps: SkirOut.BytesExpression
end

defmodule SkirOut.Point do
  @moduledoc """
  A point
  """

  use Skir.Struct,
    module_path: "@gepheum/skir-golden-tests/goldens.skir",
    qualified_name: "Point",
    doc: "A point"

  removed 0
  field(:x, :int32, 1, doc: "x coordinate")
  removed 2
  removed 3
  field :y, :int32, 4
  removed 5
  field :color, SkirOut.Color, 6
end

defmodule SkirOut.Color do
  @moduledoc false

  use Skir.Struct,
    module_path: "@gepheum/skir-golden-tests/goldens.skir",
    qualified_name: "Color"

  field :r, :int32, 0
  field :g, :int32, 1
  field :b, :int32, 2
  removed 3
end

defmodule SkirOut.MyEnum do
  @moduledoc "my enum"
  use Skir.Enum,
    module_path: "@gepheum/skir-golden-tests/goldens.skir",
    qualified_name: "MyEnum",
    doc: "my enum"

  variant :ok, 1, doc: "all good"
  removed 2
  variant :color, 4, wraps: SkirOut.Color
  variant :bool, 5, wraps: :bool
end

defmodule SkirOut.EnumA do
  @moduledoc false

  use Skir.Enum

  variant :a, 1
  variant :other, 2
end

defmodule SkirOut.EnumB do
  @moduledoc false

  use Skir.Enum

  variant :b, 1, wraps: :string
  variant :other, 2
end

defmodule SkirOut.KeyedArrays.Weekday do
  @moduledoc false

  use Skir.Enum

  variant :monday, 1
end

defmodule SkirOut.KeyedArrays.SubItem do
  @moduledoc false

  use Skir.Struct

  field :weekday, SkirOut.KeyedArrays.Weekday, 0
end

defmodule SkirOut.KeyedArrays.Item do
  @moduledoc false

  use Skir.Struct

  field :sub_item, SkirOut.KeyedArrays.SubItem, 0
end

defmodule SkirOut.KeyedArrays do
  @moduledoc false

  use Skir.Struct

  field :items, {:array, SkirOut.KeyedArrays.Item, key: [:sub_item, :weekday, :kind]}, 0
end

defmodule SkirOut.RecStruct do
  @moduledoc false

  use Skir.Struct,
    module_path: "@gepheum/skir-golden-tests/goldens.skir",
    qualified_name: "RecStruct"

  field :a, SkirOut.RecStruct, 0
  field :b, :bool, 1
end

defmodule SkirOut.RecEnum do
  @moduledoc false

  use Skir.Enum,
    module_path: "@gepheum/skir-golden-tests/goldens.skir",
    qualified_name: "RecEnum"

  variant :foo, 1
  variant :e, 2, wraps: SkirOut.RecEnum
end

defmodule SkirOut.Constants do
  @moduledoc false
  use Skir.Constants

  defconst :unit_tests, {:array, SkirOut.UnitTest}, [
    %SkirOut.UnitTest{
      test_number: 1_000,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:bool, true},
           expected_dense_json: ["1"],
           expected_readable_json: ["true"],
           alternative_jsons: [{:literal, "2.5"}, {:literal, "-1"}, {:literal, "\"1\""}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0x01>>],
           alternative_bytes: [{:to_bytes, {:float32, 2.5}}],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"primitive\",\n    \"value\": \"bool\"\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_001,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:bool, false},
           expected_dense_json: ["0"],
           expected_readable_json: ["false"],
           alternative_jsons: [{:literal, "0.0"}, {:literal, "-0.0"}, {:literal, "\"0\""}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0x00>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_002,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:timestamp, ~U[1970-01-01 00:00:00Z]},
           expected_dense_json: ["0"],
           expected_readable_json: [
             "{\n  \"unix_millis\": 0,\n  \"formatted\": \"1970-01-01T00:00:00.000Z\"\n}",
             "{\n  \"unix_millis\": 0,\n  \"formatted\": \"1970-01-01T00:00:00Z\"\n}"
           ],
           alternative_jsons: [{:literal, "0.0"}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0x00>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"primitive\",\n    \"value\": \"timestamp\"\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_003,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:timestamp, ~U[2023-08-25 21:30:34.586Z]},
           expected_dense_json: ["1692999034586"],
           expected_readable_json: [
             "{\n  \"unix_millis\": 1692999034586,\n  \"formatted\": \"2023-08-25T21:30:34.586Z\"\n}"
           ],
           alternative_jsons: [{:literal, "\"1692999034586\""}],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEF, 0xDA, 0x26, 0x9B, 0x2E, 0x8A, 0x01, 0x00, 0x00>>
           ],
           alternative_bytes: [{:to_bytes, {:float64, 1_692_999_034_586.1}}]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_004,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, 2},
           expected_dense_json: ["2"],
           expected_readable_json: ["2"],
           alternative_jsons: [{:literal, "\"2\""}, {:literal, "2.0"}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0x02>>],
           alternative_bytes: [{:to_bytes, {:float64, 2.0}}],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"primitive\",\n    \"value\": \"int32\"\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_005,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, -1},
           expected_dense_json: ["-1"],
           expected_readable_json: ["-1"],
           alternative_jsons: [{:literal, "\"-1\""}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xEB, 0xFF>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_006,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, 231},
           expected_dense_json: ["231"],
           expected_readable_json: ["231"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE7>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_007,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, 232},
           expected_dense_json: ["232"],
           expected_readable_json: ["232"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE8, 0xE8, 0x00>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_008,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, 65_535},
           expected_dense_json: ["65535"],
           expected_readable_json: ["65535"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE8, 0xFF, 0xFF>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_009,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, 65_536},
           expected_dense_json: ["65536"],
           expected_readable_json: ["65536"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE9, 0x00, 0x00, 0x01, 0x00>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_010,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, 2_147_483_647},
           expected_dense_json: ["2147483647"],
           expected_readable_json: ["2147483647"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE9, 0xFF, 0xFF, 0xFF, 0x7F>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_011,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, -255},
           expected_dense_json: ["-255"],
           expected_readable_json: ["-255"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xEB, 0x01>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_012,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, -256},
           expected_dense_json: ["-256"],
           expected_readable_json: ["-256"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xEB, 0x00>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_013,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, -257},
           expected_dense_json: ["-257"],
           expected_readable_json: ["-257"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xEC, 0xFF, 0xFE>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_014,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, -65_536},
           expected_dense_json: ["-65536"],
           expected_readable_json: ["-65536"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xEC, 0x00, 0x00>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_015,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, -65_537},
           expected_dense_json: ["-65537"],
           expected_readable_json: ["-65537"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xED, 0xFF, 0xFF, 0xFE, 0xFF>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_016,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int32, -2_147_483_648},
           expected_dense_json: ["-2147483648"],
           expected_readable_json: ["-2147483648"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xED, 0x00, 0x00, 0x00, 0x80>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_017,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, 888_888_888_888},
           expected_dense_json: ["888888888888"],
           expected_readable_json: ["888888888888"],
           alternative_jsons: [{:literal, "888888888888.0"}],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0x38, 0x0E, 0xE8, 0xF5, 0xCE, 0x00, 0x00, 0x00>>
           ],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"primitive\",\n    \"value\": \"int64\"\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_018,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, 9_223_372_036_854_775_807},
           expected_dense_json: ["\"9223372036854775807\""],
           expected_readable_json: ["\"9223372036854775807\""],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7F>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_019,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, -9_223_372_036_854_775_808},
           expected_dense_json: ["\"-9223372036854775808\""],
           expected_readable_json: ["\"-9223372036854775808\""],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_020,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, 9_007_199_254_740_991},
           expected_dense_json: ["9007199254740991"],
           expected_readable_json: ["9007199254740991"],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x1F, 0x00>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_021,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, 9_007_199_254_740_992},
           expected_dense_json: ["\"9007199254740992\""],
           expected_readable_json: ["\"9007199254740992\""],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x00>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_022,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, -9_007_199_254_740_991},
           expected_dense_json: ["-9007199254740991"],
           expected_readable_json: ["-9007199254740991"],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0xE0, 0xFF>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_023,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, -9_007_199_254_740_992},
           expected_dense_json: ["\"-9007199254740992\""],
           expected_readable_json: ["\"-9007199254740992\""],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xE0, 0xFF>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_024,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:hash64, 255},
           expected_dense_json: ["255"],
           expected_readable_json: ["255"],
           alternative_jsons: [{:literal, "255.0"}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE8, 0xFF, 0x00>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"primitive\",\n    \"value\": \"hash64\"\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_025,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:hash64, 65_535},
           expected_dense_json: ["65535"],
           expected_readable_json: ["65535"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE8, 0xFF, 0xFF>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_026,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:hash64, 4_294_967_295},
           expected_dense_json: ["4294967295"],
           expected_readable_json: ["4294967295"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE9, 0xFF, 0xFF, 0xFF, 0xFF>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_027,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:hash64, 18_446_744_073_709_551_615},
           expected_dense_json: ["\"18446744073709551615\""],
           expected_readable_json: ["\"18446744073709551615\""],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEA, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_028,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:float32, 2.5},
           expected_dense_json: ["2.5"],
           expected_readable_json: ["2.5"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF0, 0x00, 0x00, 0x20, 0x40>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"primitive\",\n    \"value\": \"float32\"\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_029,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:float64, 2.5},
           expected_dense_json: ["2.5"],
           expected_readable_json: ["2.5"],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xF1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x40>>
           ],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"primitive\",\n    \"value\": \"float64\"\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_030,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:float64, -2.5},
           expected_dense_json: ["-2.5"],
           expected_readable_json: ["-2.5"],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xF1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0xC0>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_031,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:float32, 0.0},
           expected_dense_json: ["0", "0.0"],
           expected_readable_json: ["0", "0.0"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0x00>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_032,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:string, ""},
           expected_dense_json: ["\"\""],
           expected_readable_json: ["\"\""],
           alternative_jsons: [{:literal, "0"}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF2>>],
           alternative_bytes: [{:to_bytes, {:int32, 0}}],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"primitive\",\n    \"value\": \"string\"\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_033,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:string, "Foôbar"},
           expected_dense_json: ["\"Foôbar\"", "\"Fo\\u00f4bar\""],
           expected_readable_json: ["\"Foôbar\"", "\"Fo\\u00f4bar\""],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xF3, 0x07, 0x46, 0x6F, 0xC3, 0xB4, 0x62, 0x61, 0x72>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_034,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:string, "Foo\n\"bar\""},
           expected_dense_json: ["\"Foo\\n\\\"bar\\\"\""],
           expected_readable_json: ["\"Foo\\n\\\"bar\\\"\""],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xF3, 0x09, 0x46, 0x6F, 0x6F, 0x0A, 0x22, 0x62, 0x61, 0x72,
               0x22>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_035,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:bytes, <<0xF5, 0x04, 0x69, 0xB7, 0x35>>},
           expected_dense_json: ["\"9QRptzU=\""],
           expected_readable_json: ["\"hex:f50469b735\""],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF5, 0x05, 0xF5, 0x04, 0x69, 0xB7, 0x35>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"primitive\",\n    \"value\": \"bytes\"\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_036,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:bytes, ""},
           expected_dense_json: ["\"\""],
           expected_readable_json: ["\"hex:\""],
           alternative_jsons: [{:literal, "0"}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF4>>],
           alternative_bytes: [{:to_bytes, {:int32, 0}}]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_037,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:bool_optional, nil},
           expected_dense_json: ["null"],
           expected_readable_json: ["null"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xFF>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"optional\",\n    \"value\": {\n      \"kind\": \"primitive\",\n      \"value\": \"bool\"\n    }\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_038,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:bool_optional, nil},
           expected_dense_json: ["null"],
           expected_readable_json: ["null"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xFF>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"optional\",\n    \"value\": {\n      \"kind\": \"primitive\",\n      \"value\": \"bool\"\n    }\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_039,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:ints, []},
           expected_dense_json: ["[]"],
           expected_readable_json: ["[]"],
           alternative_jsons: [{:literal, "0"}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF6>>],
           alternative_bytes: [{:to_bytes, {:int32, 0}}],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"array\",\n    \"value\": {\n      \"item\": {\n        \"kind\": \"primitive\",\n        \"value\": \"int32\"\n      }\n    }\n  },\n  \"records\": []\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_040,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:ints, [1, 2, 3]},
           expected_dense_json: ["[1,2,3]"],
           expected_readable_json: ["[\n  1,\n  2,\n  3\n]"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF9, 0x01, 0x02, 0x03>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_041,
      assertion:
        {:reserialize_large_string,
         SkirOut.Assertion.ReserializeLargeString.partial(%{
           num_chars: 231,
           expected_byte_prefix: <<0x73, 0x6B, 0x69, 0x72>>
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_042,
      assertion:
        {:reserialize_large_string,
         SkirOut.Assertion.ReserializeLargeString.partial(%{
           num_chars: 65_536,
           expected_byte_prefix: <<0x73, 0x6B, 0x69, 0x72>>
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_043,
      assertion:
        {:reserialize_large_array,
         SkirOut.Assertion.ReserializeLargeArray.partial(%{
           num_items: 231,
           expected_byte_prefix: <<0x73, 0x6B, 0x69, 0x72, 0xFA, 0xE7>>
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_044,
      assertion:
        {:reserialize_large_array,
         SkirOut.Assertion.ReserializeLargeArray.partial(%{
           num_items: 232,
           expected_byte_prefix: <<0x73, 0x6B, 0x69, 0x72, 0xFA, 0xE8, 0xE8, 0x00>>
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_045,
      assertion:
        {:reserialize_large_array,
         SkirOut.Assertion.ReserializeLargeArray.partial(%{
           num_items: 65_535,
           expected_byte_prefix: <<0x73, 0x6B, 0x69, 0x72, 0xFA, 0xE8>>
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_046,
      assertion:
        {:reserialize_large_array,
         SkirOut.Assertion.ReserializeLargeArray.partial(%{
           num_items: 65_536,
           expected_byte_prefix: <<0x73, 0x6B, 0x69, 0x72, 0xFA, 0xE9>>
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_047,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:point, SkirOut.Point.partial(%{})},
           expected_dense_json: ["[]"],
           expected_readable_json: ["{}"],
           alternative_jsons: [{:literal, "0"}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF6>>],
           alternative_bytes: [{:to_bytes, {:int32, 0}}],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"record\",\n    \"value\": \"@gepheum/skir-golden-tests/goldens.skir:Point\"\n  },\n  \"records\": [\n    {\n      \"kind\": \"struct\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:Point\",\n      \"doc\": \"A point\",\n      \"fields\": [\n        {\n          \"name\": \"x\",\n          \"number\": 1,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"int32\"\n          },\n          \"doc\": \"x coordinate\"\n        },\n        {\n          \"name\": \"y\",\n          \"number\": 4,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"int32\"\n          }\n        },\n        {\n          \"name\": \"color\",\n          \"number\": 6,\n          \"type\": {\n            \"kind\": \"record\",\n            \"value\": \"@gepheum/skir-golden-tests/goldens.skir:Color\"\n          }\n        }\n      ],\n      \"removed_numbers\": [\n        0,\n        2,\n        3,\n        5\n      ]\n    },\n    {\n      \"kind\": \"struct\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:Color\",\n      \"fields\": [\n        {\n          \"name\": \"r\",\n          \"number\": 0,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"int32\"\n          }\n        },\n        {\n          \"name\": \"g\",\n          \"number\": 1,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"int32\"\n          }\n        },\n        {\n          \"name\": \"b\",\n          \"number\": 2,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"int32\"\n          }\n        }\n      ],\n      \"removed_numbers\": [\n        3\n      ]\n    }\n  ]\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_048,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value:
             {:point, %SkirOut.Point{x: 10, y: 20, color: %SkirOut.Color{r: 255, g: 128, b: 0}}},
           expected_dense_json: ["[0,10,0,0,20,0,[255,128]]"],
           expected_readable_json: [
             "{\n  \"x\": 10,\n  \"y\": 20,\n  \"color\": {\n    \"r\": 255,\n    \"g\": 128\n  }\n}"
           ],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xFA, 0x07, 0x00, 0x0A, 0x00, 0x00, 0x14, 0x00, 0xF8, 0xE8,
               0xFF, 0x00, 0x80>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_049,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:my_enum, :unknown},
           expected_dense_json: ["0"],
           expected_readable_json: ["\"unknown\""],
           alternative_jsons: [{:literal, "\"unknown\""}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0x00>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"record\",\n    \"value\": \"@gepheum/skir-golden-tests/goldens.skir:MyEnum\"\n  },\n  \"records\": [\n    {\n      \"kind\": \"enum\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:MyEnum\",\n      \"doc\": \"my enum\",\n      \"variants\": [\n        {\n          \"name\": \"ok\",\n          \"number\": 1,\n          \"doc\": \"all good\"\n        },\n        {\n          \"name\": \"color\",\n          \"number\": 4,\n          \"type\": {\n            \"kind\": \"record\",\n            \"value\": \"@gepheum/skir-golden-tests/goldens.skir:Color\"\n          }\n        },\n        {\n          \"name\": \"bool\",\n          \"number\": 5,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"bool\"\n          }\n        }\n      ],\n      \"removed_numbers\": [\n        2\n      ]\n    },\n    {\n      \"kind\": \"struct\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:Color\",\n      \"fields\": [\n        {\n          \"name\": \"r\",\n          \"number\": 0,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"int32\"\n          }\n        },\n        {\n          \"name\": \"g\",\n          \"number\": 1,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"int32\"\n          }\n        },\n        {\n          \"name\": \"b\",\n          \"number\": 2,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"int32\"\n          }\n        }\n      ],\n      \"removed_numbers\": [\n        3\n      ]\n    }\n  ]\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_050,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:my_enum, :ok},
           expected_dense_json: ["1"],
           expected_readable_json: ["\"ok\""],
           alternative_jsons: [{:literal, "\"OK\""}],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0x01>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_051,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:my_enum, {:color, SkirOut.Color.partial(%{r: 10})}},
           expected_dense_json: ["[4,[10]]"],
           expected_readable_json: [
             "{\n  \"kind\": \"color\",\n  \"value\": {\n    \"r\": 10\n  }\n}"
           ],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xFE, 0xF7, 0x0A>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_052,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:my_enum, {:bool, true}},
           expected_dense_json: ["[5,1]"],
           expected_readable_json: ["{\n  \"kind\": \"bool\",\n  \"value\": true\n}"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF8, 0x05, 0x01>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_053,
      assertion:
        {:string_equal,
         %SkirOut.Assertion.StringEqual{
           actual:
             {:to_dense_json,
              {:point_from_json_keep_unrecognized,
               {:to_dense_json, {:ints, [2, 1, 2, 2, 1, 2, 0, 2]}}}},
           expected: {:literal, "[0,1,0,0,1,0,[],2]"}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_054,
      assertion:
        {:string_in,
         %SkirOut.Assertion.StringIn{
           actual:
             {:to_dense_json,
              {:point_from_json_drop_unrecognized,
               {:to_dense_json, {:ints, [2, 1, 2, 2, 1, 2, 0, 2]}}}},
           expected: ["[0,1,0,0,1]", "[0,1,0,0,1,0,[]]"]
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_055,
      assertion:
        {:bytes_equal,
         %SkirOut.Assertion.BytesEqual{
           actual:
             {:to_bytes,
              {:point_from_bytes_keep_unrecognized,
               {:to_bytes, {:ints, [2, 1, 2, 2, 1, 2, 0, 2]}}}},
           expected:
             {:literal,
              <<0x73, 0x6B, 0x69, 0x72, 0xFA, 0x08, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0xF6,
                0x02>>}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_056,
      assertion:
        {:bytes_in,
         %SkirOut.Assertion.BytesIn{
           actual:
             {:to_bytes,
              {:point_from_bytes_drop_unrecognized,
               {:to_bytes, {:ints, [2, 1, 2, 2, 1, 2, 0, 2]}}}},
           expected: [
             <<0x73, 0x6B, 0x69, 0x72, 0xFA, 0x05, 0x00, 0x01, 0x00, 0x00, 0x01>>,
             <<0x73, 0x6B, 0x69, 0x72, 0xFA, 0x07, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0xF6>>
           ]
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_057,
      assertion:
        {:string_equal,
         %SkirOut.Assertion.StringEqual{
           actual:
             {:to_dense_json,
              {:color_from_json_keep_unrecognized, {:to_dense_json, {:ints, [1, 1, 1, 2, 2]}}}},
           expected: {:literal, "[1,1,1,0,2]"}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_058,
      assertion:
        {:bytes_equal,
         %SkirOut.Assertion.BytesEqual{
           actual:
             {:to_bytes,
              {:color_from_bytes_keep_unrecognized, {:to_bytes, {:ints, [1, 1, 1, 2, 2]}}}},
           expected:
             {:literal, <<0x73, 0x6B, 0x69, 0x72, 0xFA, 0x05, 0x01, 0x01, 0x01, 0x00, 0x02>>}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_059,
      assertion:
        {:string_equal,
         %SkirOut.Assertion.StringEqual{
           actual:
             {:to_dense_json,
              {:my_enum_from_json_keep_unrecognized, {:to_dense_json, {:int32, 500}}}},
           expected: {:literal, "500"}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_060,
      assertion:
        {:string_equal,
         %SkirOut.Assertion.StringEqual{
           actual:
             {:to_dense_json,
              {:my_enum_from_json_drop_unrecognized, {:to_dense_json, {:int32, 500}}}},
           expected: {:literal, "0"}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_061,
      assertion:
        {:string_equal,
         %SkirOut.Assertion.StringEqual{
           actual:
             {:to_dense_json,
              {:my_enum_from_json_keep_unrecognized, {:to_dense_json, {:ints, [500, 10]}}}},
           expected: {:literal, "[500,10]"}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_062,
      assertion:
        {:string_equal,
         %SkirOut.Assertion.StringEqual{
           actual:
             {:to_dense_json,
              {:my_enum_from_json_drop_unrecognized, {:to_dense_json, {:ints, [500, 10]}}}},
           expected: {:literal, "0"}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_063,
      assertion:
        {:bytes_equal,
         %SkirOut.Assertion.BytesEqual{
           actual:
             {:to_bytes, {:my_enum_from_bytes_keep_unrecognized, {:to_bytes, {:int32, 500}}}},
           expected: {:literal, <<0x73, 0x6B, 0x69, 0x72, 0xE8, 0xF4, 0x01>>}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_064,
      assertion:
        {:bytes_equal,
         %SkirOut.Assertion.BytesEqual{
           actual:
             {:to_bytes, {:my_enum_from_bytes_drop_unrecognized, {:to_bytes, {:int32, 500}}}},
           expected: {:literal, <<0x73, 0x6B, 0x69, 0x72, 0x00>>}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_065,
      assertion:
        {:bytes_equal,
         %SkirOut.Assertion.BytesEqual{
           actual:
             {:to_bytes, {:my_enum_from_bytes_keep_unrecognized, {:to_bytes, {:ints, [500, 10]}}}},
           expected: {:literal, <<0x73, 0x6B, 0x69, 0x72, 0xF8, 0xE8, 0xF4, 0x01, 0x0A>>}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_066,
      assertion:
        {:bytes_equal,
         %SkirOut.Assertion.BytesEqual{
           actual:
             {:to_bytes, {:my_enum_from_bytes_drop_unrecognized, {:to_bytes, {:ints, [500, 10]}}}},
           expected: {:literal, <<0x73, 0x6B, 0x69, 0x72, 0x00>>}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_067,
      assertion:
        {:string_equal,
         %SkirOut.Assertion.StringEqual{
           actual:
             {:to_dense_json,
              {:color_from_bytes_keep_unrecognized, {:to_bytes, {:ints, [1, 1, 1, 2, 2]}}}},
           expected: {:literal, "[1,1,1]"}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_068,
      assertion:
        {:bytes_equal,
         %SkirOut.Assertion.BytesEqual{
           actual:
             {:to_bytes,
              {:color_from_json_keep_unrecognized, {:to_dense_json, {:ints, [1, 1, 1, 2, 2]}}}},
           expected: {:literal, <<0x73, 0x6B, 0x69, 0x72, 0xF9, 0x01, 0x01, 0x01>>}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_069,
      assertion:
        {:string_equal,
         %SkirOut.Assertion.StringEqual{
           actual:
             {:to_dense_json, {:my_enum_from_bytes_keep_unrecognized, {:to_bytes, {:int32, 500}}}},
           expected: {:literal, "0"}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_070,
      assertion:
        {:bytes_equal,
         %SkirOut.Assertion.BytesEqual{
           actual:
             {:to_bytes, {:my_enum_from_json_keep_unrecognized, {:to_dense_json, {:int32, 500}}}},
           expected: {:literal, <<0x73, 0x6B, 0x69, 0x72, 0x00>>}
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_071,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:hash64, 231},
           expected_dense_json: ["231"],
           expected_readable_json: ["231"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE7>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_072,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:hash64, 232},
           expected_dense_json: ["232"],
           expected_readable_json: ["232"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE8, 0xE8, 0x00>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_073,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, 231},
           expected_dense_json: ["231"],
           expected_readable_json: ["231"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE7>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_074,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, 232},
           expected_dense_json: ["232"],
           expected_readable_json: ["232"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xE8, 0xE8, 0x00>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_075,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:ints, [1]},
           expected_dense_json: ["[1]"],
           expected_readable_json: ["[\n  1\n]"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF7, 0x01>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_076,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:ints, [1, 2]},
           expected_dense_json: ["[1,2]"],
           expected_readable_json: ["[\n  1,\n  2\n]"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF8, 0x01, 0x02>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_077,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:ints, [1, 2, 3, 4]},
           expected_dense_json: ["[1,2,3,4]"],
           expected_readable_json: ["[\n  1,\n  2,\n  3,\n  4\n]"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xFA, 0x04, 0x01, 0x02, 0x03, 0x04>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_078,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, 4_294_967_295},
           expected_dense_json: ["4294967295"],
           expected_readable_json: ["4294967295"],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00>>,
             <<0x73, 0x6B, 0x69, 0x72, 0xE9, 0xFF, 0xFF, 0xFF, 0xFF>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_079,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, 4_294_967_296},
           expected_dense_json: ["4294967296"],
           expected_readable_json: ["4294967296"],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_080,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, -2_147_483_648},
           expected_dense_json: ["-2147483648"],
           expected_readable_json: ["-2147483648"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xED, 0x00, 0x00, 0x00, 0x80>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_081,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:int64, -2_147_483_649},
           expected_dense_json: ["-2147483649"],
           expected_readable_json: ["-2147483649"],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xEE, 0xFF, 0xFF, 0xFF, 0x7F, 0xFF, 0xFF, 0xFF, 0xFF>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_082,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:float32, :infinity},
           expected_dense_json: ["\"Infinity\""],
           expected_readable_json: ["\"Infinity\""],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF0, 0x00, 0x00, 0x80, 0x7F>>]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_083,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:float64, :neg_infinity},
           expected_dense_json: ["\"-Infinity\""],
           expected_readable_json: ["\"-Infinity\""],
           expected_bytes: [
             <<0x73, 0x6B, 0x69, 0x72, 0xF1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF0, 0xFF>>
           ]
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_084,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:keyed_arrays, SkirOut.KeyedArrays.partial(%{})},
           expected_dense_json: ["[]"],
           expected_readable_json: ["{}"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF6>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"record\",\n    \"value\": \"@gepheum/skir-golden-tests/goldens.skir:KeyedArrays\"\n  },\n  \"records\": [\n    {\n      \"kind\": \"struct\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:KeyedArrays\",\n      \"fields\": [\n        {\n          \"name\": \"items\",\n          \"number\": 0,\n          \"type\": {\n            \"kind\": \"array\",\n            \"value\": {\n              \"item\": {\n                \"kind\": \"record\",\n                \"value\": \"@gepheum/skir-golden-tests/goldens.skir:KeyedArrays.Item\"\n              },\n              \"key_extractor\": \"sub_item.weekday.kind\"\n            }\n          }\n        }\n      ]\n    },\n    {\n      \"kind\": \"struct\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:KeyedArrays.Item\",\n      \"fields\": [\n        {\n          \"name\": \"sub_item\",\n          \"number\": 0,\n          \"type\": {\n            \"kind\": \"record\",\n            \"value\": \"@gepheum/skir-golden-tests/goldens.skir:KeyedArrays.SubItem\"\n          }\n        }\n      ]\n    },\n    {\n      \"kind\": \"struct\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:KeyedArrays.SubItem\",\n      \"fields\": [\n        {\n          \"name\": \"weekday\",\n          \"number\": 0,\n          \"type\": {\n            \"kind\": \"record\",\n            \"value\": \"@gepheum/skir-golden-tests/goldens.skir:KeyedArrays.Weekday\"\n          }\n        }\n      ]\n    },\n    {\n      \"kind\": \"enum\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:KeyedArrays.Weekday\",\n      \"variants\": [\n        {\n          \"name\": \"monday\",\n          \"number\": 1\n        }\n      ]\n    }\n  ]\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_085,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value:
             {:rec_struct, %SkirOut.RecStruct{a: SkirOut.RecStruct.partial(%{b: true}), b: true}},
           expected_dense_json: ["[[[],1],1]"],
           expected_readable_json: ["{\n  \"a\": {\n    \"b\": true\n  },\n  \"b\": true\n}"],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xF8, 0xF8, 0xF6, 0x01, 0x01>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"record\",\n    \"value\": \"@gepheum/skir-golden-tests/goldens.skir:RecStruct\"\n  },\n  \"records\": [\n    {\n      \"kind\": \"struct\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:RecStruct\",\n      \"fields\": [\n        {\n          \"name\": \"a\",\n          \"number\": 0,\n          \"type\": {\n            \"kind\": \"record\",\n            \"value\": \"@gepheum/skir-golden-tests/goldens.skir:RecStruct\"\n          }\n        },\n        {\n          \"name\": \"b\",\n          \"number\": 1,\n          \"type\": {\n            \"kind\": \"primitive\",\n            \"value\": \"bool\"\n          }\n        }\n      ]\n    }\n  ]\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_086,
      assertion:
        {:reserialize_value,
         SkirOut.Assertion.ReserializeValue.partial(%{
           value: {:rec_enum, {:e, {:e, :foo}}},
           expected_dense_json: ["[2,[2,1]]"],
           expected_readable_json: [
             "{\n  \"kind\": \"e\",\n  \"value\": {\n    \"kind\": \"e\",\n    \"value\": \"foo\"\n  }\n}"
           ],
           expected_bytes: [<<0x73, 0x6B, 0x69, 0x72, 0xFC, 0xFC, 0x01>>],
           expected_type_descriptor:
             "{\n  \"type\": {\n    \"kind\": \"record\",\n    \"value\": \"@gepheum/skir-golden-tests/goldens.skir:RecEnum\"\n  },\n  \"records\": [\n    {\n      \"kind\": \"enum\",\n      \"id\": \"@gepheum/skir-golden-tests/goldens.skir:RecEnum\",\n      \"variants\": [\n        {\n          \"name\": \"foo\",\n          \"number\": 1\n        },\n        {\n          \"name\": \"e\",\n          \"number\": 2,\n          \"type\": {\n            \"kind\": \"record\",\n            \"value\": \"@gepheum/skir-golden-tests/goldens.skir:RecEnum\"\n          }\n        }\n      ]\n    }\n  ]\n}"
         })}
    },
    %SkirOut.UnitTest{
      test_number: 1_087,
      assertion:
        {:enum_a_from_json_is_constant,
         %SkirOut.Assertion.EnumAFromJsonIsConstant{
           actual:
             {:to_dense_json,
              {:enum_b_from_json_keep_unrecognized, {:to_dense_json, {:enum_a, :a}}}},
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_088,
      assertion:
        {:enum_a_from_bytes_is_constant,
         %SkirOut.Assertion.EnumAFromBytesIsConstant{
           actual:
             {:to_bytes, {:enum_b_from_bytes_keep_unrecognized, {:to_bytes, {:enum_a, :a}}}},
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_089,
      assertion:
        {:enum_b_from_json_is_wrapper_b,
         %SkirOut.Assertion.EnumBFromJsonIsWrapperB{
           actual:
             {:to_dense_json,
              {:enum_a_from_json_keep_unrecognized, {:to_dense_json, {:enum_b, {:b, "foo"}}}}},
           expected: "",
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_090,
      assertion:
        {:enum_b_from_json_is_wrapper_b,
         %SkirOut.Assertion.EnumBFromJsonIsWrapperB{
           actual:
             {:to_dense_json,
              {:enum_a_from_json_drop_unrecognized, {:to_dense_json, {:enum_b, {:b, "foo"}}}}},
           expected: "",
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_091,
      assertion:
        {:enum_b_from_bytes_is_wrapper_b,
         %SkirOut.Assertion.EnumBFromBytesIsWrapperB{
           actual:
             {:to_bytes,
              {:enum_a_from_bytes_keep_unrecognized, {:to_bytes, {:enum_b, {:b, "foo"}}}}},
           expected: "",
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_092,
      assertion:
        {:enum_b_from_bytes_is_wrapper_b,
         %SkirOut.Assertion.EnumBFromBytesIsWrapperB{
           actual:
             {:to_bytes,
              {:enum_a_from_bytes_drop_unrecognized, {:to_bytes, {:enum_b, {:b, "foo"}}}}},
           expected: "",
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_093,
      assertion:
        {:enum_b_from_json_is_wrapper_b,
         %SkirOut.Assertion.EnumBFromJsonIsWrapperB{
           actual: {:to_dense_json, {:enum_a, :a}},
           expected: "",
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_094,
      assertion:
        {:enum_b_from_bytes_is_wrapper_b,
         %SkirOut.Assertion.EnumBFromBytesIsWrapperB{
           actual: {:to_bytes, {:enum_a, :a}},
           expected: "",
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_095,
      assertion:
        {:enum_a_from_json_is_constant,
         %SkirOut.Assertion.EnumAFromJsonIsConstant{
           actual: {:to_dense_json, {:enum_b, {:b, "foo"}}},
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_096,
      assertion:
        {:enum_a_from_bytes_is_constant,
         %SkirOut.Assertion.EnumAFromBytesIsConstant{
           actual: {:to_bytes, {:enum_b, {:b, "foo"}}},
           keep_unrecognized: true
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_097,
      assertion:
        {:enum_b_from_json_is_wrapper_b,
         %SkirOut.Assertion.EnumBFromJsonIsWrapperB{
           actual: {:to_dense_json, {:enum_a, :a}},
           expected: "",
           keep_unrecognized: false
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_098,
      assertion:
        {:enum_b_from_bytes_is_wrapper_b,
         %SkirOut.Assertion.EnumBFromBytesIsWrapperB{
           actual: {:to_bytes, {:enum_a, :a}},
           expected: "",
           keep_unrecognized: false
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_099,
      assertion:
        {:enum_a_from_json_is_constant,
         %SkirOut.Assertion.EnumAFromJsonIsConstant{
           actual: {:to_dense_json, {:enum_b, {:b, "foo"}}},
           keep_unrecognized: false
         }}
    },
    %SkirOut.UnitTest{
      test_number: 1_100,
      assertion:
        {:enum_a_from_bytes_is_constant,
         %SkirOut.Assertion.EnumAFromBytesIsConstant{
           actual: {:to_bytes, {:enum_b, {:b, "foo"}}},
           keep_unrecognized: false
         }}
    }
  ]
end
